mindmap
  root((OT-3 Testing Scoping))
    hardware_subsystems[Hardware Subsystems]
        gantry_y[Gantry Y]
        gantry_x[Gantry X]
        gripper[Gripper]
        head[Gripper]
        pipettes[Pipettes]
    update_flow[Firmware Update Flow]
    odd[On-Device Display]
        sync[Sync with Desktop App]
        feature_subset[Feature Subset]
    protocols[Protocols]
    modules[Modules]
    safety[Safety]
        e_stop[E-Stop]
        door_sensor[Door Sensor]
    desktop_app[Desktop App]
    pipettes[Pipettes]
        single_channel[Single Channel]
        8_channel[8 Channel]
        96_channel[96 Channel]
        tips[Pipette Tips]
            regular[Regular Tips]
            filter[Filter Tips]
    liquid_handling[Liquid Handling]
    deck_state_mod[Deck State Modification]
