---
title: OT-3 Testing Scope Mindmap
---

flowchart LR
root("OT-3 Testing Scoping")

%%----------------------------------------------%%
hardware_subsystems("Hardware Subsystems")

gantry_y("Gantry Y")
gantry_x("Gantry X")
gripper("Gripper")
head("Gripper")
pipettes("Pipettes")
%%----------------------------------------------%%
odd("ODD")

node_layers("Node Layers")
sync("Sync between Desktop\nand ODD")
odd_recovery("ODD Recovery from Service Crash")
locked_out_features("Locked out features")
feature_subset("Feature Subset")
%%----------------------------------------------%%
networking("Networking")

odd_access("Isolate ODD to only it's own OT-3")
air_gapped("Air-gapped Network")
%%----------------------------------------------%%
update_flow("Update Flow")

scheduled_update_retrieval("Scheduled Update Retrieval")
update_interruption("Update Interruption")
update_notification("Update Notification")
%%----------------------------------------------%%
safety("Safety")

e_stop("E-Stop")
door_sensor("Door Sensor")
modules_and_e_stop("Modules and E-Stop")
e_stop_state_maintained("E-Stop State maintained between power cycles")
%%----------------------------------------------%%
protocols("Protocols")
%%----------------------------------------------%%
modules("Modules")
%%----------------------------------------------%%
desktop_app("Desktop App")
%%----------------------------------------------%%
ot3_pipettes("OT-3 Pipettes")

single_channel("Single Channel")
8_channel("8 Channel")
96_channel("96 Channel")
tips("Pipette Tips")
regular("Regular Tips")
filter_tips("Filter Tips")
%%----------------------------------------------%%
liquid_handling("Liquid Handling")
%%----------------------------------------------%%
deck_state_mod("Deck State Modification")
%%----------------------------------------------%%

root --- hardware_subsystems & odd & networking & update_flow & safety  & modules & protocols & desktop_app & ot3_pipettes & liquid_handling & deck_state_mod

hardware_subsystems --- head & gantry_x & gantry_y & gripper & pipettes
odd --- node_layers & sync & odd_recovery & locked_out_features & feature_subset
networking --- odd_access & air_gapped
update_flow --- scheduled_update_retrieval & update_interruption & update_notification
safety --- e_stop & door_sensor & modules_and_e_stop & e_stop_state_maintained

ot3_pipettes --- single_channel & 8_channel & 96_channel & tips
tips --- regular & filter_tips


classDef HardwareSubsystemBackground fill:#85edb9;
classDef ODDBackground fill:#85d1ed;
classDef NetworkingBackground fill:#f5e77f;
classDef UpdateFlowBackground fill:#f5b47f;
classDef SafetyBackground fill:#f07171;

classDef DarkText color: black;

classDef NoOutline stroke: none;
classDef DarkOutline stroke: black,stroke-width:3px;

class hardware_subsystems,gantry_y,gantry_x,gripper,head,pipettes,odd,node_layers,sync,odd_recovery,locked_out_features,feature_subset,networking,odd_access,air_gapped,update_flow,scheduled_update_retrieval,update_interruption,update_notification,e_stop,door_sensor,modules_and_e_stop,safety,e_stop_state_maintained DarkText;

class hardware_subsystems,odd,networking,update_flow,safety DarkOutline;
class gantry_y,gantry_x,gripper,head,pipettes,odd_access,air_gapped,scheduled_update_retrieval,update_interruption,update_notification,node_layers,sync,odd_recovery,locked_out_features,feature_subset,e_stop,door_sensor,modules_and_e_stop,e_stop_state_maintained NoOutline;

class hardware_subsystems,gantry_y,gantry_x,gripper,head,pipettes HardwareSubsystemBackground;
class odd,node_layers,sync,odd_recovery,locked_out_features,feature_subset ODDBackground;
class networking,odd_access,air_gapped NetworkingBackground;
class update_flow,scheduled_update_retrieval,update_interruption,update_notification UpdateFlowBackground;
class safety,e_stop,door_sensor,modules_and_e_stop,e_stop_state_maintained SafetyBackground;
